import{S as L,i as n,a as w}from"./assets/vendor-MjawMu3A.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const f=document.querySelector("#search-form"),p=document.querySelector(".gallery"),c=document.querySelector(".loader"),i=document.querySelector("#load-more");let m="",d=1,g=40,u=0;const S="53911590-e6659ac7d11975246b1e78aef",v="https://pixabay.com/api/";let q=new L(".gallery a",{captionsData:"alt",captionDelay:250});f.addEventListener("submit",P);i.addEventListener("click",M);async function P(e){e.preventDefault();const r=e.target.elements.query.value.trim();if(!r)return n.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});m=r,d=1,p.innerHTML="",i.classList.add("is-hidden"),c.style.display="block";try{const s=await y();if(u=s.totalHits,s.hits.length===0)return n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});h(s.hits),b()}catch(s){console.error(s),n.error({message:"Failed to fetch images.",position:"topRight"})}finally{c.style.display="none",f.reset()}}async function M(){d+=1,i.disabled=!0,c.style.display="block";try{const e=await y();h(e.hits),$(),b()}catch(e){console.error(e),n.error({message:"Failed to load more images.",position:"topRight"})}finally{c.style.display="none",i.disabled=!1}}async function y(){const e={key:S,q:m,image_type:"photo",orientation:"horizontal",safesearch:!0,page:d,per_page:g};return(await w.get(v,{params:e})).data}function h(e){const r=e.map(R).join("");p.insertAdjacentHTML("beforeend",r),q.refresh()}function R({webformatURL:e,largeImageURL:r,tags:s,likes:l,views:t,comments:o,downloads:a}){return`
    <li class="gallery-item">
      <a class="gallery-link" href="${r}">
        <img class="gallery-image" src="${e}" alt="${s}" />
      </a>
      <div class="info">
        <p><b>Likes</b> ${l}</p>
        <p><b>Views</b> ${t}</p>
        <p><b>Comments</b> ${o}</p>
        <p><b>Downloads</b> ${a}</p>
      </div>
    </li>
  `}function b(){d*g>=u?(i.classList.add("is-hidden"),u>0&&n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):i.classList.remove("is-hidden")}function $(){const e=p.firstElementChild;if(!e)return;const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
